# Generated by Django 4.2.16 on 2024-09-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
